#!/bin/bash
# originial script by @ubnt-stig from community.ubnt.com
# This is my attempt to optimize it.
# add your ping targets here 
targets=( 
   '1.1.1.1'        
   '8.8.8.8'        
   '8.8.4.4' 
   ) 
# latency check (true|false)
check=true
# add max latency here
max=200
[ $# != 3 ] && echo "Usages: $0 <group> <intf> <status>" exit 1
group=$1
intf=$2
status=$3
for host in "${targets[@]}"
do
pings () {
/bin/ping -n -c 4 -W 1 -w 1 -i 0.2 -I $2 $1 | tail -1 | awk -F '/' '{print $5}'
if [ ${PIPESTATUS[0]} -ne 0 ]; then
return 1
fi
}
if latency=$(pings "$host" "$intf");
then
strip=$(echo ${latency%.*})
[[ $check = "true" ]] && [[ $strip -gt $max ]] && continue
#end check latency
exit 0
fi
done
# fail
exit 1

